apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-dashboard

spec:
  replicas: 3

  selector:
    matchLabels:
      app: devops-dashboard

  template:
    metadata:
      labels:
        app: devops-dashboard

    spec:
      containers:
      - name: devops-dashboard

        image: devops-cicd-app:v2

        imagePullPolicy: Never

        ports:
        - containerPort: 80
